name: python linting

on:
  - workflow_dispatch

job:
  runson: ubuntu -latest
  lintingOperations:
    steps:
      -uses: actions/checkout@v6
      -uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      -uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8
