name: python linting

on:
  workflow_dispatch:

jobs:
  lintingOperations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Changed to write to allow the action to upload results
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8

